### ISSUE TITLE
Clean up the network configuration

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/networks-internal#235]
When Vega 0.68 is deployed, each network configuration should be updated as follow:

**Old**
```toml
Host = "127.0.0.1"
Level = "info"
Name = "fairground"
Port = 1789
TokenExpiry = "168h0m0s"

[API]

  [API.GRPC]
    Hosts = ["api.n06.testnet.vega.xyz:3007", "api.n07.testnet.vega.xyz:3007", "api.n08.testnet.vega.xyz:3007", "api.n09.testnet.vega.xyz:3007", "api.n10.testnet.vega.xyz:3007", "api.n11.testnet.vega.xyz:3007", "api.n12.testnet.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.n06.testnet.vega.xyz/graphql", "https://api.n07.testnet.vega.xyz/graphql", "https://api.n08.testnet.vega.xyz/graphql", "https://api.n09.testnet.vega.xyz/graphql", "https://api.n10.testnet.vega.xyz/graphql", "https://api.n11.testnet.vega.xyz/graphql", "https://api.n12.testnet.vega.xyz/graphql"]

  [API.REST]
    Hosts = ["https://api.n06.testnet.vega.xyz", "https://api.n07.testnet.vega.xyz", "https://api.n08.testnet.vega.xyz", "https://api.n09.testnet.vega.xyz", "https://api.n10.testnet.vega.xyz", "https://api.n11.testnet.vega.xyz", "https://api.n12.testnet.vega.xyz"]

[Console]
  LocalPort = 1847
  URL = "console.fairground.wtf"

[TokenDApp]
  LocalPort = 1848
  URL = "token.fairground.wtf"

```

**New**
```toml
Name = "fairground"

[[Metadata]]
Key = "network"
Value = "testnet"

[API]

  [API.GRPC]
    Hosts = ["api.n06.testnet.vega.xyz:3007", "api.n07.testnet.vega.xyz:3007", "api.n08.testnet.vega.xyz:3007", "api.n09.testnet.vega.xyz:3007", "api.n10.testnet.vega.xyz:3007", "api.n11.testnet.vega.xyz:3007", "api.n12.testnet.vega.xyz:3007"]
    Retries = 5

  [API.GraphQL]
    Hosts = ["https://api.n06.testnet.vega.xyz/graphql", "https://api.n07.testnet.vega.xyz/graphql", "https://api.n08.testnet.vega.xyz/graphql", "https://api.n09.testnet.vega.xyz/graphql", "https://api.n10.testnet.vega.xyz/graphql", "https://api.n11.testnet.vega.xyz/graphql", "https://api.n12.testnet.vega.xyz/graphql"]

  [API.REST]
    Hosts = ["https://api.n06.testnet.vega.xyz", "https://api.n07.testnet.vega.xyz", "https://api.n08.testnet.vega.xyz", "https://api.n09.testnet.vega.xyz", "https://api.n10.testnet.vega.xyz", "https://api.n11.testnet.vega.xyz", "https://api.n12.testnet.vega.xyz"]

[Apps]
  Console = "console.fairground.wtf"
  Governance = "token.fairground.wtf"
  Explorer = "explorer.fairground.wtf"⏎ 
```

**Note:** The metadata section should contain `network` = `testnet` when it's a testnet and `mainnet` when it's a mainnet
